### PR TITLE
:arrow_up: Drupal 7.44 => 7.56

### PR DESCRIPTION
**Pull request by nbuonin**

### CODE REVIEW

**Comment by nikolas** [comment]
epistolae is a panopoly site, and on these sites, we need to update panopoly instead of just drupal, since a panopoly version only specifically supports one drupal version, from my understanding. I follow the "Updating with drush" instructions here:
* https://www.drupal.org/node/2272177
* https://wiki.ctl.columbia.edu/index.php/Drush

We could probably use a runbook entry for this.

**Comment by nikolas** [comment]
By the way - it could be worth asking around if updating Drupal without updating Panopoly is actually fine. I'm going to ask in their irc channel.

**Comment by nbuonin** [comment]
Ok cool, but yeah I forgot about upgrading via Panopoly.  

When I upgraded Kalatheme was deleted from the `themes` directory, which should only have core themes.  I checked the base theme and its dependency was on a different theme, so I figured all was well.  I made some changes to the layout just to check that Panopoly would still work.

**Comment by nbuonin** [comment]
I'll update it with Panopoly per d.o to be safe.  It seems like there's a number of database migrations that aren't captured with the straight upgrade of Drupal core.

**Pull request closed without merging**
